# defined in torch_col/cython/dist.pyx

from typing import List, Tuple

def wait_barrier(): ...

def send_msg(src_rank: int, msg: str): ...

def recv_msg(src_rank: int) -> str: ...


def init_dynamic_batch(batch_size: int, global_batch_size: int): ...

class _DynamicBatchDistirbutor:
    def get_batch(batch_size: int) -> Tuple[List[Tuple[int, int]], bool]: ...
    def finish_batch(batch_indices: List[Tuple[int, int]]) -> None: ...
    def abort_batch(batch_indices: List[Tuple[int, int]]) -> None: ...
    def distribute_batch(check_num_unproced_samples: bool) -> None: ...
    def next_global_batch() -> None: ...

