# defined in torch_col/cython/main.pyx


def is_enable_shared_tensor() -> bool: ...

def is_enable_dynamic_sm_partition() -> bool: ...

def is_enable_xsched() -> bool: ...

def get_hook_mode() -> HookMode: ...

def is_release_interm_memory_v1() -> bool: ...

def is_release_interm_memory_v2() -> bool: ...

def disable_release_interm_memory(): ...

def disable_fbward_hook(): ...

def is_enable_fbward_hook() -> bool: ...

def torch_col_init(train_rank: int = 0, train_world_size: int = 1): ...

def get_train_rank() -> int: ...

def set_train_rank(rank): ...

def get_train_world_size() -> int: ...

def set_train_world_size(world_size): ...

def set_train_rank_world_size(rank, world_size): ...

def has_colocated_infer_server() -> bool: ...

class HookMode: ...

