TRITON_TRT_UM_HOME=$1
TRITON_TRT_INSTALL_HOME=$2

cd $TRITON_TRT_UM_HOME
cmake -DCMAKE_INSTALL_PREFIX:PATH=$TRITON_TRT_INSTALL_HOME \
    -DTRITON_COMMON_REPO_TAG=r23.12 \
    -DTRITON_CORE_REPO_TAG=r23.12 \
    -DTRITON_BACKEND_REPO_TAG=r23.12 \
    -DTRITON_TENSORRT_LIB_PATHS=$TENSORT_RT_8616_HOME/lib \
    -DTRITON_TENSORRT_INCLUDE_PATHS=$TENSORT_RT_8616_HOME/include -GNinja \
    -B build

cmake --build build 
cmake --install build