if((DEFINED CONDA_PREFIX) AND (EXISTS ${CONDA_PREFIX}/include/cudnn.h))
  set(CUDNN_INCLUDE_DIR ${CONDA_PREFIX}/include)
  set(CUDNN_LIBRARY ${CONDA_PREFIX}/lib/libcudnn.so)
  message(STATUS "Found cudnn in ${CONDA_PREFIX}")
elseif(EXISTS /usr/local/cuda/include/cudnn.h)
  set(CUDNN_INCLUDE_DIR /usr/local/cuda/include)
  set(CUDNN_LIBRARY /usr/local/cuda/lib64/libcudnn.so)
  message(STATUS "Found cudnn in /usr/lcoal/cuda")
elseif(EXISTS /usr/include/cudnn.h)
  set(CUDNN_INCLUDE_DIR /usr/include)
  set(CUDNN_LIBRARY /usr/lib/x86_64-linux-gnu/libcudnn.so)
  message(STATUS "Found cudnn in /usr")
else()
  message(STATUS "cudnn not found")
endif()